// Code generated by furo protoc-gen-open-models. DO NOT EDIT.
// protoc-gen-open-models version: ????

import { FieldNode, Registry, Value, type JSONValue } from "@furo/open-models/dist/index";


/**
 * @interface IListValue 
 *  `ListValue` is a wrapper around a repeated field of values.
 * 
 *  The JSON representation for `ListValue` is JSON array.
 */
export interface IListValue {
    /**
     *  Repeated field of dynamically typed values. 
     */
    values?: JSONValue;
}

/**
 * @interface TListValue 
 *  `ListValue` is a wrapper around a repeated field of values.
 * 
 *  The JSON representation for `ListValue` is JSON array.
 */
export interface TListValue {
/**
 *  Repeated field of dynamically typed values. 
 */
    values?: JSONValue;
}

/**
 * ListValue 
 *  `ListValue` is a wrapper around a repeated field of values.
 * 
 *  The JSON representation for `ListValue` is JSON array.
 */
export class ListValue extends FieldNode {

  /**
   * Repeated field of dynamically typed values.
   **/
  private _values: Value;

 public __defaultValues: IListValue;

  constructor(
    initData?: IListValue,
    parent?: FieldNode,
    parentAttributeName?: string,
  ) {
    super(undefined, parent, parentAttributeName);
    this.__meta.typeName = 'google.protobuf.ListValue';
    this.__meta.description = 'ListValue `ListValue` is a wrapper around a repeated field of values.\n\n The JSON representation for `ListValue` is JSON array.';

    this.__meta.nodeFields = [
      {
        fieldName: 'values',
        protoName: 'values',
        FieldConstructor: Value,
        constraints: {},
        description: 'Repeated field of dynamically typed values.'
      }
    ];

    // Initialize the fields
    // ---------------------

   /**
    *  Repeated field of dynamically typed values.
    **/
    this._values = new Value(undefined, this, 'values');



    // Set required fields
    [].forEach(fieldName => {
      (
        this[fieldName as keyof ListValue] as FieldNode
      ).__meta.required = true;
    });


    // Default values from openAPI annotations
    this.__defaultValues = {
    };

    // Initialize the fields with init data
    if (initData !== undefined) {
      this.__fromLiteral({ ...this.__defaultValues, ...initData });
    } else {
      this.__fromLiteral(this.__defaultValues);
    }

    // Set readonly fields after the init, so child nodes are readonly too
    [].forEach(fieldName => {
      (
        this[fieldName as keyof ListValue] as FieldNode
      ).__readonly = true;
    });

    this.__meta.isPristine = true;
  }

  /**
   *  Repeated field of dynamically typed values.
   * The getter receives the FieldNode
   **/
  public get values(): Value {
    return this._values;
  }

  /**
   * The setter receives `JSONValue | null`
   **/
  public set values(v: JSONValue | null) {
    this.__TypeSetter(this._values, v);
  }


  fromLiteral(data: IListValue): void {
    super.__fromLiteral(data);
  }

  toLiteral(): IListValue {
    return super.__toLiteral() as IListValue;
  }
}

Registry.register('google.protobuf.ListValue', ListValue);

