// Code generated by furo protoc-gen-open-models. DO NOT EDIT.
// protoc-gen-open-models version: ????

import { ENUM, FieldNode } from "@furo/open-models/dist/index";

//  `NullValue` is a singleton enumeration to represent the null value for the
//  `Value` type union.
// 
//  The JSON representation for `NullValue` is JSON `null`.
export enum NullValue {
//  Null value.
  NULL_VALUE = "NULL_VALUE",
}

/**
 * FieldNode for NullValue.
 * Used as the element constructor of ARRAY and the value constructor of MAP,
 * which both build their children with `new Constructor()`.
 **/
export class NullValueENUM extends ENUM<NullValue> {
  constructor(initData?: NullValue, parent?: FieldNode, parentAttributeName?: string) {
    super(initData, NullValue, NullValue.NULL_VALUE, parent, parentAttributeName);
  }
}
