// Code generated by furo protoc-gen-open-models. DO NOT EDIT.
// protoc-gen-open-models version: ????

import { FieldNode, Registry, STRING, Value, type JSONValue } from "@furo/open-models/dist/index";


/**
 * @interface IStructFieldsEntry 
 */
export interface IStructFieldsEntry {
    key?: string;
    value?: JSONValue;
}

/**
 * @interface TStructFieldsEntry 
 */
export interface TStructFieldsEntry {
    key?: string;
    value?: JSONValue;
}

/**
 * StructFieldsEntry 
 */
export class StructFieldsEntry extends FieldNode {

  /**
   **/
  private _key: STRING;

  /**
   **/
  private _value: Value;

 public __defaultValues: IStructFieldsEntry;

  constructor(
    initData?: IStructFieldsEntry,
    parent?: FieldNode,
    parentAttributeName?: string,
  ) {
    super(undefined, parent, parentAttributeName);
    this.__meta.typeName = 'google.protobuf.Struct.FieldsEntry';
    this.__meta.description = 'StructFieldsEntry';

    this.__meta.nodeFields = [
      {
        fieldName: 'key',
        protoName: 'key',
        FieldConstructor: STRING,
        constraints: {},
        description: ''
      }, 
      {
        fieldName: 'value',
        protoName: 'value',
        FieldConstructor: Value,
        constraints: {},
        description: ''
      }
    ];

    // Initialize the fields
    // ---------------------

   /**
    **/
    this._key = new STRING(undefined, this, 'key');

   /**
    **/
    this._value = new Value(undefined, this, 'value');



    // Set required fields
    [].forEach(fieldName => {
      (
        this[fieldName as keyof StructFieldsEntry] as FieldNode
      ).__meta.required = true;
    });


    // Default values from openAPI annotations
    this.__defaultValues = {
    };

    // Initialize the fields with init data
    if (initData !== undefined) {
      this.__fromLiteral({ ...this.__defaultValues, ...initData });
    } else {
      this.__fromLiteral(this.__defaultValues);
    }

    // Set readonly fields after the init, so child nodes are readonly too
    [].forEach(fieldName => {
      (
        this[fieldName as keyof StructFieldsEntry] as FieldNode
      ).__readonly = true;
    });

    this.__meta.isPristine = true;
  }

  /**
   * The getter receives the FieldNode
   **/
  public get key(): STRING {
    return this._key;
  }

  /**
   * The setter receives `string`
   **/
  public set key(v: string) {
    this.__PrimitivesSetter(this._key, v);
  }

  /**
   * The getter receives the FieldNode
   **/
  public get value(): Value {
    return this._value;
  }

  /**
   * The setter receives `JSONValue | null`
   **/
  public set value(v: JSONValue | null) {
    this.__TypeSetter(this._value, v);
  }


  fromLiteral(data: IStructFieldsEntry): void {
    super.__fromLiteral(data);
  }

  toLiteral(): IStructFieldsEntry {
    return super.__toLiteral() as IStructFieldsEntry;
  }
}

Registry.register('google.protobuf.Struct.FieldsEntry', StructFieldsEntry);

