// Code generated by furo protoc-gen-open-models. DO NOT EDIT.
// protoc-gen-open-models version: ????

import { Value as GoogleProtobufValue, type IValue as IGoogleProtobufValue, type TValue as TGoogleProtobufValue } from "./Value";

import { FieldNode, MAP, Registry } from "@furo/open-models/dist/index";


/**
 * @interface IStruct 
 *  `Struct` represents a structured data value, consisting of fields
 *  which map to dynamically typed values. In some languages, `Struct`
 *  might be supported by a native representation. For example, in
 *  scripting languages like JS a struct is represented as an
 *  object. The details of that representation are described together
 *  with the proto support for the language.
 * 
 *  The JSON representation for `Struct` is JSON object.
 */
export interface IStruct {
    /**
     *  Unordered map of dynamically typed values. 
     */
    fields?: { [key: string]: IGoogleProtobufValue };
}

/**
 * @interface TStruct 
 *  `Struct` represents a structured data value, consisting of fields
 *  which map to dynamically typed values. In some languages, `Struct`
 *  might be supported by a native representation. For example, in
 *  scripting languages like JS a struct is represented as an
 *  object. The details of that representation are described together
 *  with the proto support for the language.
 * 
 *  The JSON representation for `Struct` is JSON object.
 */
export interface TStruct {
/**
 *  Unordered map of dynamically typed values. 
 */
    fields?: { [key: string]: TGoogleProtobufValue };
}

/**
 * Struct 
 *  `Struct` represents a structured data value, consisting of fields
 *  which map to dynamically typed values. In some languages, `Struct`
 *  might be supported by a native representation. For example, in
 *  scripting languages like JS a struct is represented as an
 *  object. The details of that representation are described together
 *  with the proto support for the language.
 * 
 *  The JSON representation for `Struct` is JSON object.
 */
export class Struct extends FieldNode {

  /**
   * Unordered map of dynamically typed values.
   **/
  private _fields: MAP<string,GoogleProtobufValue,GoogleProtobufValue>;

 public __defaultValues: IStruct;

  constructor(
    initData?: IStruct,
    parent?: FieldNode,
    parentAttributeName?: string,
  ) {
    super(undefined, parent, parentAttributeName);
    this.__meta.typeName = 'google.protobuf.Struct';
    this.__meta.description = 'Struct `Struct` represents a structured data value, consisting of fields\n which map to dynamically typed values. In some languages, `Struct`\n might be supported by a native representation. For example, in\n scripting languages like JS a struct is represented as an\n object. The details of that representation are described together\n with the proto support for the language.\n\n The JSON representation for `Struct` is JSON object.';

    this.__meta.nodeFields = [
      {
        fieldName: 'fields',
        protoName: 'fields',
        FieldConstructor: MAP<string,GoogleProtobufValue,GoogleProtobufValue>,
        ValueConstructor: GoogleProtobufValue,
        constraints: {},
        description: 'Unordered map of dynamically typed values.'
      }
    ];

    // Initialize the fields
    // ---------------------

   /**
    *  Unordered map of dynamically typed values.
    **/
    this._fields = new MAP<string,GoogleProtobufValue,GoogleProtobufValue>(undefined, this, 'fields');



    // Set required fields
    [].forEach(fieldName => {
      (
        this[fieldName as keyof Struct] as FieldNode
      ).__meta.required = true;
    });


    // Default values from openAPI annotations
    this.__defaultValues = {
    };

    // Initialize the fields with init data
    if (initData !== undefined) {
      this.__fromLiteral({ ...this.__defaultValues, ...initData });
    } else {
      this.__fromLiteral(this.__defaultValues);
    }

    // Set readonly fields after the init, so child nodes are readonly too
    [].forEach(fieldName => {
      (
        this[fieldName as keyof Struct] as FieldNode
      ).__readonly = true;
    });

    this.__meta.isPristine = true;
  }

  /**
   *  Unordered map of dynamically typed values.
   * The getter receives the FieldNode
   **/
  public get fields(): MAP<string,GoogleProtobufValue,GoogleProtobufValue> {
    return this._fields;
  }

  /**
   * The setter receives `{ [key: string]: GoogleProtobufValue }`
   **/
  public set fields(v: { [key: string]: GoogleProtobufValue }) {
    this.__TypeSetter(this._fields, v);
  }


  fromLiteral(data: IStruct): void {
    super.__fromLiteral(data);
  }

  toLiteral(): IStruct {
    return super.__toLiteral() as IStruct;
  }
}

Registry.register('google.protobuf.Struct', Struct);

