// Code generated by furo protoc-gen-open-models. DO NOT EDIT.
// protoc-gen-open-models version: ????

import { NullValue as GoogleProtobufNullValue } from "./NullValue";

import { BOOLEAN, DOUBLE, ENUM, FieldNode, ListValue, Registry, STRING, Struct, type JSONObject, type JSONValue } from "@furo/open-models/dist/index";


/**
 * @interface IValue 
 *  `Value` represents a dynamically typed value which can be either
 *  null, a number, a string, a boolean, a recursive struct value, or a
 *  list of values. A producer of value is expected to set one of these
 *  variants. Absence of any variant indicates an error.
 * 
 *  The JSON representation for `Value` is JSON value.
 */
export interface IValue {
    /**
     *  Represents a null value. 
     */
    nullValue?: GoogleProtobufNullValue | string;
    /**
     *  Represents a double value. 
     */
    numberValue?: number;
    /**
     *  Represents a string value. 
     */
    stringValue?: string;
    /**
     *  Represents a boolean value. 
     */
    boolValue?: boolean;
    /**
     *  Represents a structured value. 
     */
    structValue?: JSONObject;
    /**
     *  Represents a repeated `Value`. 
     */
    listValue?: JSONValue[];
}

/**
 * @interface TValue 
 *  `Value` represents a dynamically typed value which can be either
 *  null, a number, a string, a boolean, a recursive struct value, or a
 *  list of values. A producer of value is expected to set one of these
 *  variants. Absence of any variant indicates an error.
 * 
 *  The JSON representation for `Value` is JSON value.
 */
export interface TValue {
/**
 *  Represents a null value. 
 */
    null_value?: GoogleProtobufNullValue | string;
/**
 *  Represents a double value. 
 */
    number_value?: number;
/**
 *  Represents a string value. 
 */
    string_value?: string;
/**
 *  Represents a boolean value. 
 */
    bool_value?: boolean;
/**
 *  Represents a structured value. 
 */
    struct_value?: JSONObject;
/**
 *  Represents a repeated `Value`. 
 */
    list_value?: JSONValue[];
}

/**
 * Value 
 *  `Value` represents a dynamically typed value which can be either
 *  null, a number, a string, a boolean, a recursive struct value, or a
 *  list of values. A producer of value is expected to set one of these
 *  variants. Absence of any variant indicates an error.
 * 
 *  The JSON representation for `Value` is JSON value.
 */
export class Value extends FieldNode {

  /**
   * Represents a null value.
   **/
  private _nullValue: ENUM<GoogleProtobufNullValue>;

  /**
   * Represents a double value.
   **/
  private _numberValue: DOUBLE;

  /**
   * Represents a string value.
   **/
  private _stringValue: STRING;

  /**
   * Represents a boolean value.
   **/
  private _boolValue: BOOLEAN;

  /**
   * Represents a structured value.
   **/
  private _structValue: Struct;

  /**
   * Represents a repeated `Value`.
   **/
  private _listValue: ListValue;

 public __defaultValues: IValue;

  constructor(
    initData?: IValue,
    parent?: FieldNode,
    parentAttributeName?: string,
  ) {
    super(undefined, parent, parentAttributeName);
    this.__meta.typeName = 'google.protobuf.Value';
    this.__meta.description = 'Value `Value` represents a dynamically typed value which can be either\n null, a number, a string, a boolean, a recursive struct value, or a\n list of values. A producer of value is expected to set one of these\n variants. Absence of any variant indicates an error.\n\n The JSON representation for `Value` is JSON value.';

    this.__meta.nodeFields = [
      {
        fieldName: 'nullValue',
        protoName: 'null_value',
        FieldConstructor: ENUM<GoogleProtobufNullValue>,
        constraints: {},
        description: 'Represents a null value.',
        oneofGroup: 'kind'
      }, 
      {
        fieldName: 'numberValue',
        protoName: 'number_value',
        FieldConstructor: DOUBLE,
        constraints: {},
        description: 'Represents a double value.',
        oneofGroup: 'kind'
      }, 
      {
        fieldName: 'stringValue',
        protoName: 'string_value',
        FieldConstructor: STRING,
        constraints: {},
        description: 'Represents a string value.',
        oneofGroup: 'kind'
      }, 
      {
        fieldName: 'boolValue',
        protoName: 'bool_value',
        FieldConstructor: BOOLEAN,
        constraints: {},
        description: 'Represents a boolean value.',
        oneofGroup: 'kind'
      }, 
      {
        fieldName: 'structValue',
        protoName: 'struct_value',
        FieldConstructor: Struct,
        constraints: {},
        description: 'Represents a structured value.',
        oneofGroup: 'kind'
      }, 
      {
        fieldName: 'listValue',
        protoName: 'list_value',
        FieldConstructor: ListValue,
        constraints: {},
        description: 'Represents a repeated `Value`.',
        oneofGroup: 'kind'
      }
    ];

    this.__meta.oneofGroups = new Map([
      ['kind', undefined],
    ]);

    // Initialize the fields
    // ---------------------

   /**
    *  Represents a null value.
    **/
    this._nullValue = new ENUM<GoogleProtobufNullValue>(undefined,GoogleProtobufNullValue, GoogleProtobufNullValue.NULL_VALUE,  this, 'nullValue');

   /**
    *  Represents a double value.
    **/
    this._numberValue = new DOUBLE(undefined, this, 'numberValue');

   /**
    *  Represents a string value.
    **/
    this._stringValue = new STRING(undefined, this, 'stringValue');

   /**
    *  Represents a boolean value.
    **/
    this._boolValue = new BOOLEAN(undefined, this, 'boolValue');

   /**
    *  Represents a structured value.
    **/
    this._structValue = new Struct(undefined, this, 'structValue');

   /**
    *  Represents a repeated `Value`.
    **/
    this._listValue = new ListValue(undefined, this, 'listValue');



    // Set required fields
    [].forEach(fieldName => {
      (
        this[fieldName as keyof Value] as FieldNode
      ).__meta.required = true;
    });


    // Default values from openAPI annotations
    this.__defaultValues = {
    };

    // Initialize the fields with init data
    if (initData !== undefined) {
      this.__fromLiteral({ ...this.__defaultValues, ...initData });
    } else {
      this.__fromLiteral(this.__defaultValues);
    }

    // Set readonly fields after the init, so child nodes are readonly too
    [].forEach(fieldName => {
      (
        this[fieldName as keyof Value] as FieldNode
      ).__readonly = true;
    });

    this.__meta.isPristine = true;
  }

  /**
   *  Represents a null value.
   * The getter receives the FieldNode
   **/
  public get nullValue(): ENUM<GoogleProtobufNullValue> {
    return this._nullValue;
  }

  /**
   * The setter receives `GoogleProtobufNullValue`
   **/
  public set nullValue(v: GoogleProtobufNullValue) {
    this.__TypeSetter(this._nullValue, v);
  }

  /**
   *  Represents a double value.
   * The getter receives the FieldNode
   **/
  public get numberValue(): DOUBLE {
    return this._numberValue;
  }

  /**
   * The setter receives `number`
   **/
  public set numberValue(v: number) {
    this.__PrimitivesSetter(this._numberValue, v);
  }

  /**
   *  Represents a string value.
   * The getter receives the FieldNode
   **/
  public get stringValue(): STRING {
    return this._stringValue;
  }

  /**
   * The setter receives `string`
   **/
  public set stringValue(v: string) {
    this.__PrimitivesSetter(this._stringValue, v);
  }

  /**
   *  Represents a boolean value.
   * The getter receives the FieldNode
   **/
  public get boolValue(): BOOLEAN {
    return this._boolValue;
  }

  /**
   * The setter receives `boolean`
   **/
  public set boolValue(v: boolean) {
    this.__PrimitivesSetter(this._boolValue, v);
  }

  /**
   *  Represents a structured value.
   * The getter receives the FieldNode
   **/
  public get structValue(): Struct {
    return this._structValue;
  }

  /**
   * The setter receives `JSONObject | null`
   **/
  public set structValue(v: JSONObject | null) {
    this.__TypeSetter(this._structValue, v);
  }

  /**
   *  Represents a repeated `Value`.
   * The getter receives the FieldNode
   **/
  public get listValue(): ListValue {
    return this._listValue;
  }

  /**
   * The setter receives `JSONValue[] | null`
   **/
  public set listValue(v: JSONValue[] | null) {
    this.__TypeSetter(this._listValue, v);
  }


  fromLiteral(data: IValue): void {
    super.__fromLiteral(data);
  }

  toLiteral(): IValue {
    return super.__toLiteral() as IValue;
  }
}

Registry.register('google.protobuf.Value', Value);

