// Code generated by furo protoc-gen-open-models. DO NOT EDIT.
// protoc-gen-open-models version: ????

import { ENUM, FieldNode } from "@furo/open-models/dist/index";

export enum BookingCenter {
  BOOKING_CENTER_UNSPECIFIED = "BOOKING_CENTER_UNSPECIFIED",
  GLOBAL = "GLOBAL",
  REGION_EU = "REGION_EU",
  REGION_AS = "REGION_AS",
  BBC_LI = "BBC_LI",
  BBC_AT = "BBC_AT",
  BBC_CH = "BBC_CH",
  BBC_HK = "BBC_HK",
  BBC_SG = "BBC_SG",
}

/**
 * FieldNode for BookingCenter.
 * Used as the element constructor of ARRAY and the value constructor of MAP,
 * which both build their children with `new Constructor()`.
 **/
export class BookingCenterENUM extends ENUM<BookingCenter> {
  constructor(initData?: BookingCenter, parent?: FieldNode, parentAttributeName?: string) {
    super(initData, BookingCenter, BookingCenter.BOOKING_CENTER_UNSPECIFIED, parent, parentAttributeName);
  }
}
