// Code generated by furo protoc-gen-open-models. DO NOT EDIT.
// protoc-gen-open-models version: ????

import { FieldNode, ListValue, Registry, STRING, Struct, Value, type JSONObject, type JSONValue } from "@furo/open-models/dist/index";


/**
 * @interface IDynamic 
 *  Fields whose JSON shape is not fixed by the proto.
 */
export interface IDynamic {
    /**
     *  Any JSON value: a string, a number, a bool, null, an object or an array. 
     */
    value?: JSONValue;
    /**
     *  A JSON array. 
     */
    listValue?: JSONValue[];
    /**
     *  A JSON object. 
     */
    structValue?: JSONObject;
    /**
     *  A plain field next to them, to see its name mapped while theirs are not. 
     */
    displayName?: string;
}

/**
 * @interface TDynamic 
 *  Fields whose JSON shape is not fixed by the proto.
 */
export interface TDynamic {
/**
 *  Any JSON value: a string, a number, a bool, null, an object or an array. 
 */
    value?: JSONValue;
/**
 *  A JSON array. 
 */
    list_value?: JSONValue[];
/**
 *  A JSON object. 
 */
    struct_value?: JSONObject;
/**
 *  A plain field next to them, to see its name mapped while theirs are not. 
 */
    display_name?: string;
}

/**
 * Dynamic 
 *  Fields whose JSON shape is not fixed by the proto.
 */
export class Dynamic extends FieldNode {

  /**
   * Any JSON value: a string, a number, a bool, null, an object or an array.
   **/
  private _value: Value;

  /**
   * A JSON array.
   **/
  private _listValue: ListValue;

  /**
   * A JSON object.
   **/
  private _structValue: Struct;

  /**
   * A plain field next to them, to see its name mapped while theirs are not.
   **/
  private _displayName: STRING;

 public __defaultValues: IDynamic;

  constructor(
    initData?: IDynamic,
    parent?: FieldNode,
    parentAttributeName?: string,
  ) {
    super(undefined, parent, parentAttributeName);
    this.__meta.typeName = 'furo.type.Dynamic';
    this.__meta.description = 'Dynamic Fields whose JSON shape is not fixed by the proto.';

    this.__meta.nodeFields = [
      {
        fieldName: 'value',
        protoName: 'value',
        FieldConstructor: Value,
        constraints: {},
        description: 'Any JSON value: a string, a number, a bool, null, an object or an array.'
      }, 
      {
        fieldName: 'listValue',
        protoName: 'list_value',
        FieldConstructor: ListValue,
        constraints: {},
        description: 'A JSON array.'
      }, 
      {
        fieldName: 'structValue',
        protoName: 'struct_value',
        FieldConstructor: Struct,
        constraints: {},
        description: 'A JSON object.'
      }, 
      {
        fieldName: 'displayName',
        protoName: 'display_name',
        FieldConstructor: STRING,
        constraints: {},
        description: 'A plain field next to them, to see its name mapped while theirs are not.'
      }
    ];

    // Initialize the fields
    // ---------------------

   /**
    *  Any JSON value: a string, a number, a bool, null, an object or an array.
    **/
    this._value = new Value(undefined, this, 'value');

   /**
    *  A JSON array.
    **/
    this._listValue = new ListValue(undefined, this, 'listValue');

   /**
    *  A JSON object.
    **/
    this._structValue = new Struct(undefined, this, 'structValue');

   /**
    *  A plain field next to them, to see its name mapped while theirs are not.
    **/
    this._displayName = new STRING(undefined, this, 'displayName');



    // Set required fields
    [].forEach(fieldName => {
      (
        this[fieldName as keyof Dynamic] as FieldNode
      ).__meta.required = true;
    });


    // Default values from openAPI annotations
    this.__defaultValues = {
    };

    // Initialize the fields with init data
    if (initData !== undefined) {
      this.__fromLiteral({ ...this.__defaultValues, ...initData });
    } else {
      this.__fromLiteral(this.__defaultValues);
    }

    // Set readonly fields after the init, so child nodes are readonly too
    [].forEach(fieldName => {
      (
        this[fieldName as keyof Dynamic] as FieldNode
      ).__readonly = true;
    });

    this.__meta.isPristine = true;
  }

  /**
   *  Any JSON value: a string, a number, a bool, null, an object or an array.
   * The getter receives the FieldNode
   **/
  public get value(): Value {
    return this._value;
  }

  /**
   * The setter receives `JSONValue | null`
   **/
  public set value(v: JSONValue | null) {
    this.__TypeSetter(this._value, v);
  }

  /**
   *  A JSON array.
   * The getter receives the FieldNode
   **/
  public get listValue(): ListValue {
    return this._listValue;
  }

  /**
   * The setter receives `JSONValue[] | null`
   **/
  public set listValue(v: JSONValue[] | null) {
    this.__TypeSetter(this._listValue, v);
  }

  /**
   *  A JSON object.
   * The getter receives the FieldNode
   **/
  public get structValue(): Struct {
    return this._structValue;
  }

  /**
   * The setter receives `JSONObject | null`
   **/
  public set structValue(v: JSONObject | null) {
    this.__TypeSetter(this._structValue, v);
  }

  /**
   *  A plain field next to them, to see its name mapped while theirs are not.
   * The getter receives the FieldNode
   **/
  public get displayName(): STRING {
    return this._displayName;
  }

  /**
   * The setter receives `string`
   **/
  public set displayName(v: string) {
    this.__PrimitivesSetter(this._displayName, v);
  }


  fromLiteral(data: IDynamic): void {
    super.__fromLiteral(data);
  }

  toLiteral(): IDynamic {
    return super.__toLiteral() as IDynamic;
  }
}

Registry.register('furo.type.Dynamic', Dynamic);

