// Code generated by furo protoc-gen-open-models. DO NOT EDIT.
// protoc-gen-open-models version: ????

import {
  DeepRecursion as FuroTypeDeepRecursion,
  type IDeepRecursion as IFuroTypeDeepRecursion,
  type TDeepRecursion as TFuroTypeDeepRecursion,
} from "./DeepRecursion";

import { FieldNode, RECURSION, Registry } from "@furo/open-models/dist/index";

/**
 * @interface IOther
 */
export interface IOther {
  recursion?: IFuroTypeDeepRecursion;
}

/**
 * @interface TOther
 */
export interface TOther {
  recursion?: TFuroTypeDeepRecursion;
}

/**
 * Other
 */
export class Other extends FieldNode {
  /**
   **/
  private _recursion: RECURSION<FuroTypeDeepRecursion, IFuroTypeDeepRecursion>;

  public __defaultValues: IOther;

  constructor(initData?: IOther, parent?: FieldNode, parentAttributeName?: string) {
    super(undefined, parent, parentAttributeName);
    this.__meta.typeName = "furo.type.Other";
    this.__meta.description = "Other";

    this.__meta.nodeFields = [
      {
        fieldName: "recursion",
        protoName: "recursion",
        FieldConstructor: FuroTypeDeepRecursion,
        constraints: {},
        description: "",
      },
    ];

    // Initialize the fields
    // ---------------------

    /**
     **/
    this._recursion = new RECURSION<FuroTypeDeepRecursion, IFuroTypeDeepRecursion>(undefined, this, "recursion");

    // Set required fields
    [].forEach(fieldName => {
      (this[fieldName as keyof Other] as FieldNode).__meta.required = true;
    });

    // Default values from openAPI annotations
    this.__defaultValues = {};

    // Initialize the fields with init data
    if (initData !== undefined) {
      this.__fromLiteral({ ...this.__defaultValues, ...initData });
    } else {
      this.__fromLiteral(this.__defaultValues);
    }

    // Set readonly fields after the init, so child nodes are readonly too
    [].forEach(fieldName => {
      (this[fieldName as keyof Other] as FieldNode).__readonly = true;
    });

    this.__meta.isPristine = true;
  }

  /**
   * The getter receives the FieldNode
   **/
  public get recursion(): RECURSION<FuroTypeDeepRecursion, IFuroTypeDeepRecursion> {
    return this._recursion;
  }

  /**
   * The setter receives `IFuroTypeDeepRecursion | null`
   **/
  public set recursion(v: IFuroTypeDeepRecursion | null) {
    this.__TypeSetter(this._recursion, v);
  }

  fromLiteral(data: IOther): void {
    super.__fromLiteral(data);
  }

  toLiteral(): IOther {
    return super.__toLiteral() as IOther;
  }
}

Registry.register("furo.type.Other", Other);
