// Code generated by furo protoc-gen-open-models. DO NOT EDIT.
// protoc-gen-open-models version: ????

import { ENUM, FieldNode } from "@furo/open-models/dist/index";

export enum RefSystem {
  REF_SYSTEM_UNSPECIFIED = "REF_SYSTEM_UNSPECIFIED",
  ACP = "ACP",
  ICM = "ICM",
  DATAFACTORY = "DATAFACTORY",
  HEIMDALL = "HEIMDALL",
  CRM = "CRM",
  CLM = "CLM",
  LOKI = "LOKI",
  DIGIMON = "DIGIMON",
  AD = "AD",
  MATRIX = "MATRIX",
}

/**
 * FieldNode for RefSystem.
 * Used as the element constructor of ARRAY and the value constructor of MAP,
 * which both build their children with `new Constructor()`.
 **/
export class RefSystemENUM extends ENUM<RefSystem> {
  constructor(initData?: RefSystem, parent?: FieldNode, parentAttributeName?: string) {
    super(initData, RefSystem, RefSystem.REF_SYSTEM_UNSPECIFIED, parent, parentAttributeName);
  }
}
