// Code generated by furo protoc-gen-open-models. DO NOT EDIT.
// protoc-gen-open-models version: ????

import {
  FLOAT,
  FieldNode,
  INT32,
  Registry,
} from '@furo/open-models/dist/index';

/**
 * @interface IColour
 *  Colour is a rgba color
 */
export interface IColour {
  /**
   *  the red part of the color
   */
  red?: number;
  /**
   *  the green part of the color
   */
  green?: number;
  /**
   *  the blue part of the color
   */
  blue?: number;
  alpha?: number;
}

/**
 * @interface TColour
 *  Colour is a rgba color
 */
export interface TColour {
  /**
   *  the red part of the color
   */
  red?: number;
  /**
   *  the green part of the color
   */
  green?: number;
  /**
   *  the blue part of the color
   */
  blue?: number;
  alpha?: number;
}

/**
 * Colour
 *  Colour is a rgba color
 */
export class Colour extends FieldNode {
  //  the red part of the color
  private _red: INT32;

  //  the green part of the color
  private _green: INT32;

  //  the blue part of the color
  private _blue: INT32;

  private _alpha: FLOAT;

  public __defaultValues: IColour;

  constructor(
    initData?: IColour,
    parent?: FieldNode,
    parentAttributeName?: string,
  ) {
    super(undefined, parent, parentAttributeName);
    this.__meta.typeName = 'furo.cube.Colour';
    this.__meta.description = 'Colour Colour is a rgba color';

    this.__meta.nodeFields = [
      {
        fieldName: 'red',
        protoName: 'red',
        FieldConstructor: INT32,
        constraints: { maximum: 255 },
        description: 'the red part of the color',
      },
      {
        fieldName: 'green',
        protoName: 'green',
        FieldConstructor: INT32,
        constraints: { maximum: 255 },
        description: 'the green part of the color',
      },
      {
        fieldName: 'blue',
        protoName: 'blue',
        FieldConstructor: INT32,
        constraints: { maximum: 255 },
        description: 'the blue part of the color',
      },
      {
        fieldName: 'alpha',
        protoName: 'alpha',
        FieldConstructor: FLOAT,
        constraints: { maximum: 1 },
        description: '',
      },
    ];

    // Initialize the fields
    //  the red part of the color
    this._red = new INT32(undefined, this, 'red');

    //  the green part of the color
    this._green = new INT32(undefined, this, 'green');

    //  the blue part of the color
    this._blue = new INT32(undefined, this, 'blue');

    this._alpha = new FLOAT(undefined, this, 'alpha');

    // Set required fields
    [].forEach(fieldName => {
      (this[fieldName as keyof Colour] as FieldNode).__meta.required = true;
    });

    // Default values from openAPI annotations
    this.__defaultValues = {
      alpha: 1.0,
      blue: 88.0,
      green: 34.0,
      red: 22.0,
    };

    // Initialize the fields with init data
    if (initData !== undefined) {
      this.__fromLiteral({ ...this.__defaultValues, ...initData });
    } else {
      this.__fromLiteral(this.__defaultValues);
    }

    // Set readonly fields after the init, so child nodes are readonly too
    [].forEach(fieldName => {
      (this[fieldName as keyof Colour] as FieldNode).__readonly = true;
    });

    this.__meta.isPristine = true;
  }

  //  the red part of the color
  public get red(): INT32 {
    return this._red;
  }

  public set red(v: number) {
    this.__PrimitivesSetter(this._red, v);
  }

  //  the green part of the color
  public get green(): INT32 {
    return this._green;
  }

  public set green(v: number) {
    this.__PrimitivesSetter(this._green, v);
  }

  //  the blue part of the color
  public get blue(): INT32 {
    return this._blue;
  }

  public set blue(v: number) {
    this.__PrimitivesSetter(this._blue, v);
  }

  public get alpha(): FLOAT {
    return this._alpha;
  }

  public set alpha(v: number) {
    this.__PrimitivesSetter(this._alpha, v);
  }

  fromLiteral(data: IColour) {
    super.__fromLiteral(data);
  }

  toLiteral(): IColour {
    return super.__toLiteral();
  }
}

Registry.register('furo.cube.Colour', Colour);
