// Code generated by furo protoc-gen-open-models. DO NOT EDIT.
// protoc-gen-open-models version: ????

import {
  DOUBLE,
  ENUM,
  FieldNode,
  Registry,
} from '@furo/open-models/dist/index';
import {
  Colour as FuroCubeColour,
  type IColour as IFuroCubeColour,
  type TColour as TFuroCubeColour,
} from './Colour';

import { Materials as FuroCubeMaterials } from './Materials';

/**
 * @interface ICubeDefinition
 *  CubeDefinition is a definition of a cube.
 */
export interface ICubeDefinition {
  /**
   *  the length of the cube in cm
   */
  length?: number;
  /**
   *  the breadth / width of the cube in cm
   */
  breadth?: number;
  /**
   *  the height of the cube in cm
   */
  height?: number;
  /**
   *  the color of the cube
   */
  colour?: IFuroCubeColour;
  /**
   *  The material the cube is made of
   */
  material?: FuroCubeMaterials | string;
}

/**
 * @interface TCubeDefinition
 *  CubeDefinition is a definition of a cube.
 */
export interface TCubeDefinition {
  /**
   *  the length of the cube in cm
   */
  length?: number;
  /**
   *  the breadth / width of the cube in cm
   */
  breadth?: number;
  /**
   *  the height of the cube in cm
   */
  height?: number;
  /**
   *  the color of the cube
   */
  colour?: TFuroCubeColour;
  /**
   *  The material the cube is made of
   */
  material?: FuroCubeMaterials | string;
}

/**
 * CubeDefinition
 *  CubeDefinition is a definition of a cube.
 */
export class CubeDefinition extends FieldNode {
  //  the length of the cube in cm
  private _length: DOUBLE;

  //  the breadth / width of the cube in cm
  private _breadth: DOUBLE;

  //  the height of the cube in cm
  private _height: DOUBLE;

  //  the color of the cube
  private _colour: FuroCubeColour;

  //  The material the cube is made of
  private _material: ENUM<FuroCubeMaterials>;

  public __defaultValues: ICubeDefinition;

  constructor(
    initData?: ICubeDefinition,
    parent?: FieldNode,
    parentAttributeName?: string,
  ) {
    super(undefined, parent, parentAttributeName);
    this.__meta.typeName = 'furo.cube.CubeDefinition';
    this.__meta.description =
      'CubeDefinition CubeDefinition is a definition of a cube.';

    this.__meta.nodeFields = [
      {
        fieldName: 'length',
        protoName: 'length',
        FieldConstructor: DOUBLE,
        constraints: { maximum: 1000, minimum: 100, required: true },
        description: 'the length of the cube in cm',
      },
      {
        fieldName: 'breadth',
        protoName: 'breadth',
        FieldConstructor: DOUBLE,
        constraints: { maximum: 1000, minimum: 100, required: true },
        description: 'the breadth / width of the cube in cm',
      },
      {
        fieldName: 'height',
        protoName: 'height',
        FieldConstructor: DOUBLE,
        constraints: { maximum: 1000, minimum: 100, required: true },
        description: 'the height of the cube in cm',
      },
      {
        fieldName: 'colour',
        protoName: 'colour',
        FieldConstructor: FuroCubeColour,
        constraints: {},
        description: 'the color of the cube',
      },
      {
        fieldName: 'material',
        protoName: 'material',
        FieldConstructor: ENUM<FuroCubeMaterials>,
        constraints: {},
        description: 'The material the cube is made of',
      },
    ];

    // Initialize the fields
    //  the length of the cube in cm
    this._length = new DOUBLE(undefined, this, 'length');

    //  the breadth / width of the cube in cm
    this._breadth = new DOUBLE(undefined, this, 'breadth');

    //  the height of the cube in cm
    this._height = new DOUBLE(undefined, this, 'height');

    //  the color of the cube
    this._colour = new FuroCubeColour(undefined, this, 'colour');

    //  The material the cube is made of
    this._material = new ENUM<FuroCubeMaterials>(
      undefined,
      FuroCubeMaterials,
      FuroCubeMaterials.MATERIALS_UNSPECIFIED,
      this,
      'material',
    );

    // Set required fields
    ['length', 'breadth', 'height'].forEach(fieldName => {
      (this[fieldName as keyof CubeDefinition] as FieldNode).__meta.required =
        true;
    });

    // Default values from openAPI annotations
    this.__defaultValues = {
      breadth: 100.0,
      height: 100.0,
      length: 100.0,
    };

    // Initialize the fields with init data
    if (initData !== undefined) {
      this.__fromLiteral({ ...this.__defaultValues, ...initData });
    } else {
      this.__fromLiteral(this.__defaultValues);
    }

    // Set readonly fields after the init, so child nodes are readonly too
    [].forEach(fieldName => {
      (this[fieldName as keyof CubeDefinition] as FieldNode).__readonly = true;
    });

    this.__meta.isPristine = true;
  }

  //  the length of the cube in cm
  public get length(): DOUBLE {
    return this._length;
  }

  public set length(v: number) {
    this.__PrimitivesSetter(this._length, v);
  }

  //  the breadth / width of the cube in cm
  public get breadth(): DOUBLE {
    return this._breadth;
  }

  public set breadth(v: number) {
    this.__PrimitivesSetter(this._breadth, v);
  }

  //  the height of the cube in cm
  public get height(): DOUBLE {
    return this._height;
  }

  public set height(v: number) {
    this.__PrimitivesSetter(this._height, v);
  }

  //  the color of the cube
  public get colour(): FuroCubeColour {
    return this._colour;
  }

  public set colour(v: IFuroCubeColour) {
    this.__TypeSetter(this._colour, v);
  }

  //  The material the cube is made of
  public get material(): ENUM<FuroCubeMaterials> {
    return this._material;
  }

  public set material(v: FuroCubeMaterials) {
    this.__TypeSetter(this._material, v);
  }

  fromLiteral(data: ICubeDefinition) {
    super.__fromLiteral(data);
  }

  toLiteral(): ICubeDefinition {
    return super.__toLiteral();
  }
}

Registry.register('furo.cube.CubeDefinition', CubeDefinition);
