// Code generated by furo protoc-gen-open-models. DO NOT EDIT.
// protoc-gen-open-models version: ????

import { CubeEntity as FuroCubeCubeEntity, type ICubeEntity as IFuroCubeCubeEntity, type TCubeEntity as TFuroCubeCubeEntity } from "./CubeEntity";

import { ARRAY, FieldNode, Registry } from "@furo/open-models/dist/index";

/**
 * @interface ICubeServiceGetListResponse
 */
export interface ICubeServiceGetListResponse {
  entities?: IFuroCubeCubeEntity[];
}

/**
 * @interface TCubeServiceGetListResponse
 */
export interface TCubeServiceGetListResponse {
  entities?: TFuroCubeCubeEntity[];
}

/**
 * CubeServiceGetListResponse
 */
export class CubeServiceGetListResponse extends FieldNode {
  /**
   **/
  private _entities: ARRAY<FuroCubeCubeEntity, IFuroCubeCubeEntity>;

  public __defaultValues: ICubeServiceGetListResponse;

  constructor(initData?: ICubeServiceGetListResponse, parent?: FieldNode, parentAttributeName?: string) {
    super(undefined, parent, parentAttributeName);
    this.__meta.typeName = "furo.cube.CubeServiceGetListResponse";
    this.__meta.description = "CubeServiceGetListResponse";

    this.__meta.nodeFields = [
      {
        fieldName: "entities",
        protoName: "entities",
        FieldConstructor: FuroCubeCubeEntity,
        constraints: {},
        description: "",
      },
    ];

    // Initialize the fields
    // ---------------------

    /**
     **/
    this._entities = new ARRAY<FuroCubeCubeEntity, IFuroCubeCubeEntity>(undefined, this, "entities");

    // Set required fields
    [].forEach(fieldName => {
      (this[fieldName as keyof CubeServiceGetListResponse] as FieldNode).__meta.required = true;
    });

    // Default values from openAPI annotations
    this.__defaultValues = {};

    // Initialize the fields with init data
    if (initData !== undefined) {
      this.__fromLiteral({ ...this.__defaultValues, ...initData });
    } else {
      this.__fromLiteral(this.__defaultValues);
    }

    // Set readonly fields after the init, so child nodes are readonly too
    [].forEach(fieldName => {
      (this[fieldName as keyof CubeServiceGetListResponse] as FieldNode).__readonly = true;
    });

    this.__meta.isPristine = true;
  }

  /**
   * The getter receives the FieldNode
   **/
  public get entities(): ARRAY<FuroCubeCubeEntity, IFuroCubeCubeEntity> {
    return this._entities;
  }

  /**
   * The setter receives `IFuroCubeCubeEntity[] | null`
   **/
  public set entities(v: IFuroCubeCubeEntity[] | null) {
    this.__TypeSetter(this._entities, v);
  }

  fromLiteral(data: ICubeServiceGetListResponse): void {
    super.__fromLiteral(data);
  }

  toLiteral(): ICubeServiceGetListResponse {
    return super.__toLiteral() as ICubeServiceGetListResponse;
  }
}

Registry.register("furo.cube.CubeServiceGetListResponse", CubeServiceGetListResponse);
