// Code generated by furo protoc-gen-open-models. DO NOT EDIT.
// protoc-gen-open-models version: ????

import { FieldNode, Registry, STRING } from "@furo/open-models/dist/index";

/**
 * @interface ICubeServiceWatchRequest
 */
export interface ICubeServiceWatchRequest {
  /**
   *  only report on this cube, all of them when empty
   */
  cubeId?: string;
}

/**
 * @interface TCubeServiceWatchRequest
 */
export interface TCubeServiceWatchRequest {
  /**
   *  only report on this cube, all of them when empty
   */
  cube_id?: string;
}

/**
 * CubeServiceWatchRequest
 */
export class CubeServiceWatchRequest extends FieldNode {
  /**
   * only report on this cube, all of them when empty
   **/
  private _cubeId: STRING;

  public __defaultValues: ICubeServiceWatchRequest;

  constructor(initData?: ICubeServiceWatchRequest, parent?: FieldNode, parentAttributeName?: string) {
    super(undefined, parent, parentAttributeName);
    this.__meta.typeName = "furo.cube.CubeServiceWatchRequest";
    this.__meta.description = "CubeServiceWatchRequest";

    this.__meta.nodeFields = [
      {
        fieldName: "cubeId",
        protoName: "cube_id",
        FieldConstructor: STRING,
        constraints: {},
        description: "only report on this cube, all of them when empty",
      },
    ];

    // Initialize the fields
    // ---------------------

    /**
     *  only report on this cube, all of them when empty
     **/
    this._cubeId = new STRING(undefined, this, "cubeId");

    // Set required fields
    [].forEach(fieldName => {
      (this[fieldName as keyof CubeServiceWatchRequest] as FieldNode).__meta.required = true;
    });

    // Default values from openAPI annotations
    this.__defaultValues = {};

    // Initialize the fields with init data
    if (initData !== undefined) {
      this.__fromLiteral({ ...this.__defaultValues, ...initData });
    } else {
      this.__fromLiteral(this.__defaultValues);
    }

    // Set readonly fields after the init, so child nodes are readonly too
    [].forEach(fieldName => {
      (this[fieldName as keyof CubeServiceWatchRequest] as FieldNode).__readonly = true;
    });

    this.__meta.isPristine = true;
  }

  /**
   *  only report on this cube, all of them when empty
   * The getter receives the FieldNode
   **/
  public get cubeId(): STRING {
    return this._cubeId;
  }

  /**
   * The setter receives `string`
   **/
  public set cubeId(v: string) {
    this.__PrimitivesSetter(this._cubeId, v);
  }

  fromLiteral(data: ICubeServiceWatchRequest): void {
    super.__fromLiteral(data);
  }

  toLiteral(): ICubeServiceWatchRequest {
    return super.__toLiteral() as ICubeServiceWatchRequest;
  }
}

Registry.register("furo.cube.CubeServiceWatchRequest", CubeServiceWatchRequest);
