// Code generated by furo protoc-gen-open-models. DO NOT EDIT.
// protoc-gen-open-models version: ????

import { Materials as FuroCubeMaterials } from "./Materials";

import { ENUM, FieldNode, Registry, STRING } from "@furo/open-models/dist/index";

/**
 * @interface ICubeDefinitionMaterialByPartEntry
 */
export interface ICubeDefinitionMaterialByPartEntry {
  key?: string;
  value?: FuroCubeMaterials | string;
}

/**
 * @interface TCubeDefinitionMaterialByPartEntry
 */
export interface TCubeDefinitionMaterialByPartEntry {
  key?: string;
  value?: FuroCubeMaterials | string;
}

/**
 * CubeDefinitionMaterialByPartEntry
 */
export class CubeDefinitionMaterialByPartEntry extends FieldNode {
  /**
   **/
  private _key: STRING;

  /**
   **/
  private _value: ENUM<FuroCubeMaterials>;

  public __defaultValues: ICubeDefinitionMaterialByPartEntry;

  constructor(initData?: ICubeDefinitionMaterialByPartEntry, parent?: FieldNode, parentAttributeName?: string) {
    super(undefined, parent, parentAttributeName);
    this.__meta.typeName = "furo.cube.CubeDefinition.MaterialByPartEntry";
    this.__meta.description = "CubeDefinitionMaterialByPartEntry";

    this.__meta.nodeFields = [
      {
        fieldName: "key",
        protoName: "key",
        FieldConstructor: STRING,
        constraints: {},
        description: "",
      },
      {
        fieldName: "value",
        protoName: "value",
        FieldConstructor: ENUM<FuroCubeMaterials>,
        constraints: {},
        description: "",
      },
    ];

    // Initialize the fields
    // ---------------------

    /**
     **/
    this._key = new STRING(undefined, this, "key");

    /**
     **/
    this._value = new ENUM<FuroCubeMaterials>(undefined, FuroCubeMaterials, FuroCubeMaterials.MATERIALS_UNSPECIFIED, this, "value");

    // Set required fields
    [].forEach(fieldName => {
      (this[fieldName as keyof CubeDefinitionMaterialByPartEntry] as FieldNode).__meta.required = true;
    });

    // Default values from openAPI annotations
    this.__defaultValues = {};

    // Initialize the fields with init data
    if (initData !== undefined) {
      this.__fromLiteral({ ...this.__defaultValues, ...initData });
    } else {
      this.__fromLiteral(this.__defaultValues);
    }

    // Set readonly fields after the init, so child nodes are readonly too
    [].forEach(fieldName => {
      (this[fieldName as keyof CubeDefinitionMaterialByPartEntry] as FieldNode).__readonly = true;
    });

    this.__meta.isPristine = true;
  }

  /**
   * The getter receives the FieldNode
   **/
  public get key(): STRING {
    return this._key;
  }

  /**
   * The setter receives `string`
   **/
  public set key(v: string) {
    this.__PrimitivesSetter(this._key, v);
  }

  /**
   * The getter receives the FieldNode
   **/
  public get value(): ENUM<FuroCubeMaterials> {
    return this._value;
  }

  /**
   * The setter receives `FuroCubeMaterials`
   **/
  public set value(v: FuroCubeMaterials) {
    this.__TypeSetter(this._value, v);
  }

  fromLiteral(data: ICubeDefinitionMaterialByPartEntry): void {
    super.__fromLiteral(data);
  }

  toLiteral(): ICubeDefinitionMaterialByPartEntry {
    return super.__toLiteral() as ICubeDefinitionMaterialByPartEntry;
  }
}

Registry.register("furo.cube.CubeDefinition.MaterialByPartEntry", CubeDefinitionMaterialByPartEntry);
