// Code generated by furo protoc-gen-open-models. DO NOT EDIT.
// protoc-gen-open-models version: ????

import { Fetcher } from '@furo/open-models/dist/Fetcher';
import { StrictFetcher } from '@furo/open-models/dist/StrictFetcher';
import { API_OPTIONS } from '../../API_OPTIONS';

import {
  CubeServiceGetListRequest as FuroCubeCubeServiceGetListRequest,
  type ICubeServiceGetListRequest as IFuroCubeCubeServiceGetListRequest,
} from './CubeServiceGetListRequest';

import {
  CubeServiceGetListResponse as FuroCubeCubeServiceGetListResponse,
  type ICubeServiceGetListResponse as IFuroCubeCubeServiceGetListResponse,
} from './CubeServiceGetListResponse';

import {
  CubeServiceGetRequest as FuroCubeCubeServiceGetRequest,
  type ICubeServiceGetRequest as IFuroCubeCubeServiceGetRequest,
} from './CubeServiceGetRequest';

import {
  CubeServiceGetResponse as FuroCubeCubeServiceGetResponse,
  type ICubeServiceGetResponse as IFuroCubeCubeServiceGetResponse,
} from './CubeServiceGetResponse';

import {
  CubeServiceUpdateRequest as FuroCubeCubeServiceUpdateRequest,
  type ICubeServiceUpdateRequest as IFuroCubeCubeServiceUpdateRequest,
} from './CubeServiceUpdateRequest';

import {
  CubeServiceUpdateResponse as FuroCubeCubeServiceUpdateResponse,
  type ICubeServiceUpdateResponse as IFuroCubeCubeServiceUpdateResponse,
} from './CubeServiceUpdateResponse';

//  cube services

export class CubeService {
  //  Get a list of cubes
  public GetList: Fetcher<
    IFuroCubeCubeServiceGetListRequest,
    IFuroCubeCubeServiceGetListResponse
  > = new Fetcher<
    IFuroCubeCubeServiceGetListRequest,
    IFuroCubeCubeServiceGetListResponse
  >(API_OPTIONS, 'GET', '/v1/cubes'); //  trailing

  public Get: Fetcher<
    IFuroCubeCubeServiceGetRequest,
    IFuroCubeCubeServiceGetResponse
  > = new Fetcher<
    IFuroCubeCubeServiceGetRequest,
    IFuroCubeCubeServiceGetResponse
  >(API_OPTIONS, 'GET', '/v1/cubes/{cube_id}');

  public Update: Fetcher<
    IFuroCubeCubeServiceUpdateRequest,
    IFuroCubeCubeServiceUpdateResponse
  > = new Fetcher<
    IFuroCubeCubeServiceUpdateRequest,
    IFuroCubeCubeServiceUpdateResponse
  >(API_OPTIONS, 'PUT', '/v1/cubes/{cube_id}', 'entity');
}

//  cube services with StrictFetcher (FieldNode-based conversion)

export class StrictCubeService {
  //  Get a list of cubes
  public GetList: StrictFetcher<
    IFuroCubeCubeServiceGetListRequest,
    IFuroCubeCubeServiceGetListResponse
  > = new StrictFetcher<
    IFuroCubeCubeServiceGetListRequest,
    IFuroCubeCubeServiceGetListResponse
  >(API_OPTIONS, 'GET', '/v1/cubes', FuroCubeCubeServiceGetListRequest, FuroCubeCubeServiceGetListResponse);

  public Get: StrictFetcher<
    IFuroCubeCubeServiceGetRequest,
    IFuroCubeCubeServiceGetResponse
  > = new StrictFetcher<
    IFuroCubeCubeServiceGetRequest,
    IFuroCubeCubeServiceGetResponse
  >(API_OPTIONS, 'GET', '/v1/cubes/{cube_id}', FuroCubeCubeServiceGetRequest, FuroCubeCubeServiceGetResponse);

  public Update: StrictFetcher<
    IFuroCubeCubeServiceUpdateRequest,
    IFuroCubeCubeServiceUpdateResponse
  > = new StrictFetcher<
    IFuroCubeCubeServiceUpdateRequest,
    IFuroCubeCubeServiceUpdateResponse
  >(API_OPTIONS, 'PUT', '/v1/cubes/{cube_id}', FuroCubeCubeServiceUpdateRequest, FuroCubeCubeServiceUpdateResponse, 'entity');
}
