// Code generated by furo protoc-gen-open-models. DO NOT EDIT.
// protoc-gen-open-models version: ????

import { CubeDeleted as FuroCubeCubeDeleted, type ICubeDeleted as IFuroCubeCubeDeleted, type TCubeDeleted as TFuroCubeCubeDeleted } from "./CubeDeleted";

import { CubeEntity as FuroCubeCubeEntity, type ICubeEntity as IFuroCubeCubeEntity, type TCubeEntity as TFuroCubeCubeEntity } from "./CubeEntity";

import {
  CubeHeartbeat as FuroCubeCubeHeartbeat,
  type ICubeHeartbeat as IFuroCubeCubeHeartbeat,
  type TCubeHeartbeat as TFuroCubeCubeHeartbeat,
} from "./CubeHeartbeat";

import { FieldNode, Registry } from "@furo/open-models/dist/index";

/**
 * @interface ICubeEvent
 *  One event of the cube stream. The name of the set `payload` member is the SSE event name.
 */
export interface ICubeEvent {
  /**
   *  a cube was created
   */
  cubeCreated?: IFuroCubeCubeEntity;
  /**
   *  a cube was deleted, the payload is its id
   */
  cubeDeleted?: IFuroCubeCubeDeleted;
  /**
   *  the keepalive: it carries no `event:` name, so it arrives as the SSE default type `message`
   */
  message?: IFuroCubeCubeHeartbeat;
}

/**
 * @interface TCubeEvent
 *  One event of the cube stream. The name of the set `payload` member is the SSE event name.
 */
export interface TCubeEvent {
  /**
   *  a cube was created
   */
  cube_created?: TFuroCubeCubeEntity;
  /**
   *  a cube was deleted, the payload is its id
   */
  cube_deleted?: TFuroCubeCubeDeleted;
  /**
   *  the keepalive: it carries no `event:` name, so it arrives as the SSE default type `message`
   */
  message?: TFuroCubeCubeHeartbeat;
}

/**
 * CubeEvent
 *  One event of the cube stream. The name of the set `payload` member is the SSE event name.
 */
export class CubeEvent extends FieldNode {
  /**
   * a cube was created
   **/
  private _cubeCreated: FuroCubeCubeEntity;

  /**
   * a cube was deleted, the payload is its id
   **/
  private _cubeDeleted: FuroCubeCubeDeleted;

  /**
   * the keepalive: it carries no `event:` name, so it arrives as the SSE default type `message`
   **/
  private _message: FuroCubeCubeHeartbeat;

  public __defaultValues: ICubeEvent;

  constructor(initData?: ICubeEvent, parent?: FieldNode, parentAttributeName?: string) {
    super(undefined, parent, parentAttributeName);
    this.__meta.typeName = "furo.cube.CubeEvent";
    this.__meta.description = "CubeEvent One event of the cube stream. The name of the set `payload` member is the SSE event name.";

    this.__meta.nodeFields = [
      {
        fieldName: "cubeCreated",
        protoName: "cube_created",
        FieldConstructor: FuroCubeCubeEntity,
        constraints: {},
        description: "a cube was created",
        oneofGroup: "payload",
      },
      {
        fieldName: "cubeDeleted",
        protoName: "cube_deleted",
        FieldConstructor: FuroCubeCubeDeleted,
        constraints: {},
        description: "a cube was deleted, the payload is its id",
        oneofGroup: "payload",
      },
      {
        fieldName: "message",
        protoName: "message",
        FieldConstructor: FuroCubeCubeHeartbeat,
        constraints: {},
        description: "the keepalive: it carries no `event:` name, so it arrives as the SSE default type `message`",
        oneofGroup: "payload",
      },
    ];

    this.__meta.oneofGroups = new Map([["payload", undefined]]);

    // Initialize the fields
    // ---------------------

    /**
     *  a cube was created
     **/
    this._cubeCreated = new FuroCubeCubeEntity(undefined, this, "cubeCreated");

    /**
     *  a cube was deleted, the payload is its id
     **/
    this._cubeDeleted = new FuroCubeCubeDeleted(undefined, this, "cubeDeleted");

    /**
     *  the keepalive: it carries no `event:` name, so it arrives as the SSE default type `message`
     **/
    this._message = new FuroCubeCubeHeartbeat(undefined, this, "message");

    // Set required fields
    [].forEach(fieldName => {
      (this[fieldName as keyof CubeEvent] as FieldNode).__meta.required = true;
    });

    // Default values from openAPI annotations
    this.__defaultValues = {};

    // Initialize the fields with init data
    if (initData !== undefined) {
      this.__fromLiteral({ ...this.__defaultValues, ...initData });
    } else {
      this.__fromLiteral(this.__defaultValues);
    }

    // Set readonly fields after the init, so child nodes are readonly too
    [].forEach(fieldName => {
      (this[fieldName as keyof CubeEvent] as FieldNode).__readonly = true;
    });

    this.__meta.isPristine = true;
  }

  /**
   *  a cube was created
   * The getter receives the FieldNode
   **/
  public get cubeCreated(): FuroCubeCubeEntity {
    return this._cubeCreated;
  }

  /**
   * The setter receives `IFuroCubeCubeEntity | null`
   **/
  public set cubeCreated(v: IFuroCubeCubeEntity | null) {
    this.__TypeSetter(this._cubeCreated, v);
  }

  /**
   *  a cube was deleted, the payload is its id
   * The getter receives the FieldNode
   **/
  public get cubeDeleted(): FuroCubeCubeDeleted {
    return this._cubeDeleted;
  }

  /**
   * The setter receives `IFuroCubeCubeDeleted | null`
   **/
  public set cubeDeleted(v: IFuroCubeCubeDeleted | null) {
    this.__TypeSetter(this._cubeDeleted, v);
  }

  /**
   *  the keepalive: it carries no `event:` name, so it arrives as the SSE default type `message`
   * The getter receives the FieldNode
   **/
  public get message(): FuroCubeCubeHeartbeat {
    return this._message;
  }

  /**
   * The setter receives `IFuroCubeCubeHeartbeat | null`
   **/
  public set message(v: IFuroCubeCubeHeartbeat | null) {
    this.__TypeSetter(this._message, v);
  }

  fromLiteral(data: ICubeEvent): void {
    super.__fromLiteral(data);
  }

  toLiteral(): ICubeEvent {
    return super.__toLiteral() as ICubeEvent;
  }
}

Registry.register("furo.cube.CubeEvent", CubeEvent);
