// Code generated by furo protoc-gen-open-models. DO NOT EDIT.
// protoc-gen-open-models version: ????

import { FieldNode, INT32, Registry } from "@furo/open-models/dist/index";

/**
 * @interface ICubeHeartbeat
 */
export interface ICubeHeartbeat {
  count?: number;
}

/**
 * @interface TCubeHeartbeat
 */
export interface TCubeHeartbeat {
  count?: number;
}

/**
 * CubeHeartbeat
 */
export class CubeHeartbeat extends FieldNode {
  /**
   **/
  private _count: INT32;

  public __defaultValues: ICubeHeartbeat;

  constructor(initData?: ICubeHeartbeat, parent?: FieldNode, parentAttributeName?: string) {
    super(undefined, parent, parentAttributeName);
    this.__meta.typeName = "furo.cube.CubeHeartbeat";
    this.__meta.description = "CubeHeartbeat";

    this.__meta.nodeFields = [
      {
        fieldName: "count",
        protoName: "count",
        FieldConstructor: INT32,
        constraints: {},
        description: "",
      },
    ];

    // Initialize the fields
    // ---------------------

    /**
     **/
    this._count = new INT32(undefined, this, "count");

    // Set required fields
    [].forEach(fieldName => {
      (this[fieldName as keyof CubeHeartbeat] as FieldNode).__meta.required = true;
    });

    // Default values from openAPI annotations
    this.__defaultValues = {};

    // Initialize the fields with init data
    if (initData !== undefined) {
      this.__fromLiteral({ ...this.__defaultValues, ...initData });
    } else {
      this.__fromLiteral(this.__defaultValues);
    }

    // Set readonly fields after the init, so child nodes are readonly too
    [].forEach(fieldName => {
      (this[fieldName as keyof CubeHeartbeat] as FieldNode).__readonly = true;
    });

    this.__meta.isPristine = true;
  }

  /**
   * The getter receives the FieldNode
   **/
  public get count(): INT32 {
    return this._count;
  }

  /**
   * The setter receives `number`
   **/
  public set count(v: number) {
    this.__PrimitivesSetter(this._count, v);
  }

  fromLiteral(data: ICubeHeartbeat): void {
    super.__fromLiteral(data);
  }

  toLiteral(): ICubeHeartbeat {
    return super.__toLiteral() as ICubeHeartbeat;
  }
}

Registry.register("furo.cube.CubeHeartbeat", CubeHeartbeat);
