// Code generated by furo protoc-gen-open-models. DO NOT EDIT.
// protoc-gen-open-models version: ????

import { CubeEntity as FuroCubeCubeEntity, type ICubeEntity as IFuroCubeCubeEntity, type TCubeEntity as TFuroCubeCubeEntity } from "./CubeEntity";

import { FieldNode, Registry } from "@furo/open-models/dist/index";

/**
 * @interface ICubeServiceUpdateResponse
 */
export interface ICubeServiceUpdateResponse {
  entity?: IFuroCubeCubeEntity;
}

/**
 * @interface TCubeServiceUpdateResponse
 */
export interface TCubeServiceUpdateResponse {
  entity?: TFuroCubeCubeEntity;
}

/**
 * CubeServiceUpdateResponse
 */
export class CubeServiceUpdateResponse extends FieldNode {
  /**
   **/
  private _entity: FuroCubeCubeEntity;

  public __defaultValues: ICubeServiceUpdateResponse;

  constructor(initData?: ICubeServiceUpdateResponse, parent?: FieldNode, parentAttributeName?: string) {
    super(undefined, parent, parentAttributeName);
    this.__meta.typeName = "furo.cube.CubeServiceUpdateResponse";
    this.__meta.description = "CubeServiceUpdateResponse";

    this.__meta.nodeFields = [
      {
        fieldName: "entity",
        protoName: "entity",
        FieldConstructor: FuroCubeCubeEntity,
        constraints: {},
        description: "",
      },
    ];

    // Initialize the fields
    // ---------------------

    /**
     **/
    this._entity = new FuroCubeCubeEntity(undefined, this, "entity");

    // Set required fields
    [].forEach(fieldName => {
      (this[fieldName as keyof CubeServiceUpdateResponse] as FieldNode).__meta.required = true;
    });

    // Default values from openAPI annotations
    this.__defaultValues = {};

    // Initialize the fields with init data
    if (initData !== undefined) {
      this.__fromLiteral({ ...this.__defaultValues, ...initData });
    } else {
      this.__fromLiteral(this.__defaultValues);
    }

    // Set readonly fields after the init, so child nodes are readonly too
    [].forEach(fieldName => {
      (this[fieldName as keyof CubeServiceUpdateResponse] as FieldNode).__readonly = true;
    });

    this.__meta.isPristine = true;
  }

  /**
   * The getter receives the FieldNode
   **/
  public get entity(): FuroCubeCubeEntity {
    return this._entity;
  }

  /**
   * The setter receives `IFuroCubeCubeEntity | null`
   **/
  public set entity(v: IFuroCubeCubeEntity | null) {
    this.__TypeSetter(this._entity, v);
  }

  fromLiteral(data: ICubeServiceUpdateResponse): void {
    super.__fromLiteral(data);
  }

  toLiteral(): ICubeServiceUpdateResponse {
    return super.__toLiteral() as ICubeServiceUpdateResponse;
  }
}

Registry.register("furo.cube.CubeServiceUpdateResponse", CubeServiceUpdateResponse);
