// Code generated by furo protoc-gen-open-models. DO NOT EDIT.
// protoc-gen-open-models version: ????

import { Colour as FuroCubeColour, type IColour as IFuroCubeColour, type TColour as TFuroCubeColour } from "./Colour";

import { Materials as FuroCubeMaterials } from "./Materials";

import { DOUBLE, ENUM, FieldNode, INT64, Registry, STRING } from "@furo/open-models/dist/index";

/**
 * @interface ICubeDefinition
 *  CubeDefinition is a definition of a cube.
 */
export interface ICubeDefinition {
  /**
   *  the length of the cube in cm
   */
  length?: number;
  /**
   *  the breadth / width of the cube in cm
   */
  breadth?: number;
  /**
   *  the height of the cube in cm
   */
  height?: number;
  /**
   *  the color of the cube
   */
  colour?: IFuroCubeColour;
  /**
   *  The material the cube is made of
   */
  material?: FuroCubeMaterials | string;
  name?: string;
  subMessage?: IFuroCubeColour;
  otherName?: string;
  intNumber?: string;
}

/**
 * @interface TCubeDefinition
 *  CubeDefinition is a definition of a cube.
 */
export interface TCubeDefinition {
  /**
   *  the length of the cube in cm
   */
  length?: number;
  /**
   *  the breadth / width of the cube in cm
   */
  breadth?: number;
  /**
   *  the height of the cube in cm
   */
  height?: number;
  /**
   *  the color of the cube
   */
  colour?: TFuroCubeColour;
  /**
   *  The material the cube is made of
   */
  material?: FuroCubeMaterials | string;
  name?: string;
  sub_message?: TFuroCubeColour;
  other_name?: string;
  int_number?: string;
}

/**
 * CubeDefinition
 *  CubeDefinition is a definition of a cube.
 */
export class CubeDefinition extends FieldNode {
  /**
   * the length of the cube in cm
   **/
  private _length: DOUBLE;

  /**
   * the breadth / width of the cube in cm
   **/
  private _breadth: DOUBLE;

  /**
   * the height of the cube in cm
   **/
  private _height: DOUBLE;

  /**
   * the color of the cube
   **/
  private _colour: FuroCubeColour;

  /**
   * The material the cube is made of
   **/
  private _material: ENUM<FuroCubeMaterials>;

  /**
   **/
  private _name: STRING;

  /**
   **/
  private _subMessage: FuroCubeColour;

  /**
   **/
  private _otherName: STRING;

  /**
   **/
  private _intNumber: INT64;

  public __defaultValues: ICubeDefinition;

  constructor(initData?: ICubeDefinition, parent?: FieldNode, parentAttributeName?: string) {
    super(undefined, parent, parentAttributeName);
    this.__meta.typeName = "furo.cube.CubeDefinition";
    this.__meta.description = "CubeDefinition CubeDefinition is a definition of a cube.";

    this.__meta.nodeFields = [
      {
        fieldName: "length",
        protoName: "length",
        FieldConstructor: DOUBLE,
        constraints: { maximum: 1000, minimum: 100, required: true },
        description: "the length of the cube in cm",
      },
      {
        fieldName: "breadth",
        protoName: "breadth",
        FieldConstructor: DOUBLE,
        constraints: { maximum: 1000, minimum: 100, required: true },
        description: "the breadth / width of the cube in cm",
      },
      {
        fieldName: "height",
        protoName: "height",
        FieldConstructor: DOUBLE,
        constraints: { maximum: 1000, minimum: 100, required: true },
        description: "the height of the cube in cm",
      },
      {
        fieldName: "colour",
        protoName: "colour",
        FieldConstructor: FuroCubeColour,
        constraints: {},
        description: "the color of the cube",
      },
      {
        fieldName: "material",
        protoName: "material",
        FieldConstructor: ENUM<FuroCubeMaterials>,
        constraints: {},
        description: "The material the cube is made of",
      },
      {
        fieldName: "name",
        protoName: "name",
        FieldConstructor: STRING,
        constraints: {},
        description: "",
        oneofGroup: "testOneof",
      },
      {
        fieldName: "subMessage",
        protoName: "sub_message",
        FieldConstructor: FuroCubeColour,
        constraints: {},
        description: "",
        oneofGroup: "testOneof",
      },
      {
        fieldName: "otherName",
        protoName: "other_name",
        FieldConstructor: STRING,
        constraints: {},
        description: "",
        oneofGroup: "otherOneof",
      },
      {
        fieldName: "intNumber",
        protoName: "int_number",
        FieldConstructor: INT64,
        constraints: {},
        description: "",
        oneofGroup: "otherOneof",
      },
    ];

    this.__meta.oneofGroups = new Map([
      ["testOneof", undefined],
      ["otherOneof", undefined],
    ]);

    // Initialize the fields
    // ---------------------

    /**
     *  the length of the cube in cm
     **/
    this._length = new DOUBLE(undefined, this, "length");

    /**
     *  the breadth / width of the cube in cm
     **/
    this._breadth = new DOUBLE(undefined, this, "breadth");

    /**
     *  the height of the cube in cm
     **/
    this._height = new DOUBLE(undefined, this, "height");

    /**
     *  the color of the cube
     **/
    this._colour = new FuroCubeColour(undefined, this, "colour");

    /**
     *  The material the cube is made of
     **/
    this._material = new ENUM<FuroCubeMaterials>(undefined, FuroCubeMaterials, FuroCubeMaterials.MATERIALS_UNSPECIFIED, this, "material");

    /**
     **/
    this._name = new STRING(undefined, this, "name");

    /**
     **/
    this._subMessage = new FuroCubeColour(undefined, this, "subMessage");

    /**
     **/
    this._otherName = new STRING(undefined, this, "otherName");

    /**
     **/
    this._intNumber = new INT64(undefined, this, "intNumber");

    // Set required fields
    ["length", "breadth", "height"].forEach(fieldName => {
      (this[fieldName as keyof CubeDefinition] as FieldNode).__meta.required = true;
    });

    // Default values from openAPI annotations
    this.__defaultValues = {
      breadth: 100.0,
      height: 100.0,
      length: 100.0,
    };

    // Initialize the fields with init data
    if (initData !== undefined) {
      this.__fromLiteral({ ...this.__defaultValues, ...initData });
    } else {
      this.__fromLiteral(this.__defaultValues);
    }

    // Set readonly fields after the init, so child nodes are readonly too
    [].forEach(fieldName => {
      (this[fieldName as keyof CubeDefinition] as FieldNode).__readonly = true;
    });

    this.__meta.isPristine = true;
  }

  /**
   *  the length of the cube in cm
   * The getter receives the FieldNode
   **/
  public get length(): DOUBLE {
    return this._length;
  }

  /**
   * The setter receives `number`
   **/
  public set length(v: number) {
    this.__PrimitivesSetter(this._length, v);
  }

  /**
   *  the breadth / width of the cube in cm
   * The getter receives the FieldNode
   **/
  public get breadth(): DOUBLE {
    return this._breadth;
  }

  /**
   * The setter receives `number`
   **/
  public set breadth(v: number) {
    this.__PrimitivesSetter(this._breadth, v);
  }

  /**
   *  the height of the cube in cm
   * The getter receives the FieldNode
   **/
  public get height(): DOUBLE {
    return this._height;
  }

  /**
   * The setter receives `number`
   **/
  public set height(v: number) {
    this.__PrimitivesSetter(this._height, v);
  }

  /**
   *  the color of the cube
   * The getter receives the FieldNode
   **/
  public get colour(): FuroCubeColour {
    return this._colour;
  }

  /**
   * The setter receives `IFuroCubeColour`
   **/
  public set colour(v: IFuroCubeColour) {
    this.__TypeSetter(this._colour, v);
  }

  /**
   *  The material the cube is made of
   * The getter receives the FieldNode
   **/
  public get material(): ENUM<FuroCubeMaterials> {
    return this._material;
  }

  /**
   * The setter receives `FuroCubeMaterials`
   **/
  public set material(v: FuroCubeMaterials) {
    this.__TypeSetter(this._material, v);
  }

  /**
   * The getter receives the FieldNode
   **/
  public get name(): STRING {
    return this._name;
  }

  /**
   * The setter receives `string`
   **/
  public set name(v: string) {
    this.__PrimitivesSetter(this._name, v);
  }

  /**
   * The getter receives the FieldNode
   **/
  public get subMessage(): FuroCubeColour {
    return this._subMessage;
  }

  /**
   * The setter receives `IFuroCubeColour`
   **/
  public set subMessage(v: IFuroCubeColour) {
    this.__TypeSetter(this._subMessage, v);
  }

  /**
   * The getter receives the FieldNode
   **/
  public get otherName(): STRING {
    return this._otherName;
  }

  /**
   * The setter receives `string`
   **/
  public set otherName(v: string) {
    this.__PrimitivesSetter(this._otherName, v);
  }

  /**
   * The getter receives the FieldNode
   **/
  public get intNumber(): INT64 {
    return this._intNumber;
  }

  /**
   * The setter receives `bigint`
   **/
  public set intNumber(v: bigint) {
    this.__PrimitivesSetter(this._intNumber, v);
  }

  fromLiteral(data: ICubeDefinition): void {
    super.__fromLiteral(data);
  }

  toLiteral(): ICubeDefinition {
    return super.__toLiteral() as ICubeDefinition;
  }
}

Registry.register("furo.cube.CubeDefinition", CubeDefinition);
