// Code generated by furo protoc-gen-open-models. DO NOT EDIT.
// protoc-gen-open-models version: ????

import { FieldNode, Registry, STRING } from "@furo/open-models/dist/index";

/**
 * @interface ICubeDeleted
 */
export interface ICubeDeleted {
  cubeId?: string;
}

/**
 * @interface TCubeDeleted
 */
export interface TCubeDeleted {
  cube_id?: string;
}

/**
 * CubeDeleted
 */
export class CubeDeleted extends FieldNode {
  /**
   **/
  private _cubeId: STRING;

  public __defaultValues: ICubeDeleted;

  constructor(initData?: ICubeDeleted, parent?: FieldNode, parentAttributeName?: string) {
    super(undefined, parent, parentAttributeName);
    this.__meta.typeName = "furo.cube.CubeDeleted";
    this.__meta.description = "CubeDeleted";

    this.__meta.nodeFields = [
      {
        fieldName: "cubeId",
        protoName: "cube_id",
        FieldConstructor: STRING,
        constraints: {},
        description: "",
      },
    ];

    // Initialize the fields
    // ---------------------

    /**
     **/
    this._cubeId = new STRING(undefined, this, "cubeId");

    // Set required fields
    [].forEach(fieldName => {
      (this[fieldName as keyof CubeDeleted] as FieldNode).__meta.required = true;
    });

    // Default values from openAPI annotations
    this.__defaultValues = {};

    // Initialize the fields with init data
    if (initData !== undefined) {
      this.__fromLiteral({ ...this.__defaultValues, ...initData });
    } else {
      this.__fromLiteral(this.__defaultValues);
    }

    // Set readonly fields after the init, so child nodes are readonly too
    [].forEach(fieldName => {
      (this[fieldName as keyof CubeDeleted] as FieldNode).__readonly = true;
    });

    this.__meta.isPristine = true;
  }

  /**
   * The getter receives the FieldNode
   **/
  public get cubeId(): STRING {
    return this._cubeId;
  }

  /**
   * The setter receives `string`
   **/
  public set cubeId(v: string) {
    this.__PrimitivesSetter(this._cubeId, v);
  }

  fromLiteral(data: ICubeDeleted): void {
    super.__fromLiteral(data);
  }

  toLiteral(): ICubeDeleted {
    return super.__toLiteral() as ICubeDeleted;
  }
}

Registry.register("furo.cube.CubeDeleted", CubeDeleted);
