// Code generated by furo protoc-gen-open-models. DO NOT EDIT.
// protoc-gen-open-models version: ????

import {
  CubeDefinition as FuroCubeCubeDefinition,
  type ICubeDefinition as IFuroCubeCubeDefinition,
  type TCubeDefinition as TFuroCubeCubeDefinition,
} from "./CubeDefinition";

import { FieldNode, Registry, STRING } from "@furo/open-models/dist/index";

/**
 * @interface ICubeEntity
 *  CubeEntity
 */
export interface ICubeEntity {
  /**
   *  human-readable name for the cube entity
   */
  displayName?: string;
  /**
   *  short and nice description of the cube
   */
  description?: string;
  /**
   *  Definition of the cube
   */
  cube?: IFuroCubeCubeDefinition;
}

/**
 * @interface TCubeEntity
 *  CubeEntity
 */
export interface TCubeEntity {
  /**
   *  human-readable name for the cube entity
   */
  display_name?: string;
  /**
   *  short and nice description of the cube
   */
  description?: string;
  /**
   *  Definition of the cube
   */
  cube?: TFuroCubeCubeDefinition;
}

/**
 * CubeEntity
 *  CubeEntity
 */
export class CubeEntity extends FieldNode {
  /**
   * human-readable name for the cube entity
   **/
  private _displayName: STRING;

  /**
   * short and nice description of the cube
   **/
  private _description: STRING;

  /**
   * Definition of the cube
   **/
  private _cube: FuroCubeCubeDefinition;

  public __defaultValues: ICubeEntity;

  constructor(initData?: ICubeEntity, parent?: FieldNode, parentAttributeName?: string) {
    super(undefined, parent, parentAttributeName);
    this.__meta.typeName = "furo.cube.CubeEntity";
    this.__meta.description = "CubeEntity CubeEntity";

    this.__meta.nodeFields = [
      {
        fieldName: "displayName",
        protoName: "display_name",
        FieldConstructor: STRING,
        constraints: { read_only: true },
        description: "human-readable name for the cube entity",
      },
      {
        fieldName: "description",
        protoName: "description",
        FieldConstructor: STRING,
        constraints: {},
        description: "short and nice description of the cube",
      },
      {
        fieldName: "cube",
        protoName: "cube",
        FieldConstructor: FuroCubeCubeDefinition,
        constraints: {},
        description: "Definition of the cube",
      },
    ];

    // Initialize the fields
    // ---------------------

    /**
     *  human-readable name for the cube entity
     **/
    this._displayName = new STRING(undefined, this, "displayName");

    /**
     *  short and nice description of the cube
     **/
    this._description = new STRING(undefined, this, "description");

    /**
     *  Definition of the cube
     **/
    this._cube = new FuroCubeCubeDefinition(undefined, this, "cube");

    // Set required fields
    [].forEach(fieldName => {
      (this[fieldName as keyof CubeEntity] as FieldNode).__meta.required = true;
    });

    // Default values from openAPI annotations
    this.__defaultValues = {
      cube: { length: 222 },
    };

    // Initialize the fields with init data
    if (initData !== undefined) {
      this.__fromLiteral({ ...this.__defaultValues, ...initData });
    } else {
      this.__fromLiteral(this.__defaultValues);
    }

    // Set readonly fields after the init, so child nodes are readonly too
    ["displayName"].forEach(fieldName => {
      (this[fieldName as keyof CubeEntity] as FieldNode).__readonly = true;
    });

    this.__meta.isPristine = true;
  }

  /**
   *  human-readable name for the cube entity
   * The getter receives the FieldNode
   **/
  public get displayName(): STRING {
    return this._displayName;
  }

  /**
   * The setter receives `string`
   **/
  public set displayName(v: string) {
    this.__PrimitivesSetter(this._displayName, v);
  }

  /**
   *  short and nice description of the cube
   * The getter receives the FieldNode
   **/
  public get description(): STRING {
    return this._description;
  }

  /**
   * The setter receives `string`
   **/
  public set description(v: string) {
    this.__PrimitivesSetter(this._description, v);
  }

  /**
   *  Definition of the cube
   * The getter receives the FieldNode
   **/
  public get cube(): FuroCubeCubeDefinition {
    return this._cube;
  }

  /**
   * The setter receives `IFuroCubeCubeDefinition`
   **/
  public set cube(v: IFuroCubeCubeDefinition) {
    this.__TypeSetter(this._cube, v);
  }

  fromLiteral(data: ICubeEntity): void {
    super.__fromLiteral(data);
  }

  toLiteral(): ICubeEntity {
    return super.__toLiteral() as ICubeEntity;
  }
}

Registry.register("furo.cube.CubeEntity", CubeEntity);
