// Code generated by furo protoc-gen-open-models. DO NOT EDIT.
// protoc-gen-open-models version: ????

export enum BookingCenter {
  BOOKING_CENTER_UNSPECIFIED = 'BOOKING_CENTER_UNSPECIFIED',
  GLOBAL = 'GLOBAL',
  REGION_EU = 'REGION_EU',
  REGION_AS = 'REGION_AS',
  BBC_LI = 'BBC_LI',
  BBC_AT = 'BBC_AT',
  BBC_CH = 'BBC_CH',
  BBC_HK = 'BBC_HK',
  BBC_SG = 'BBC_SG',
}
