// Code generated by furo protoc-gen-open-models. DO NOT EDIT.
// protoc-gen-open-models version: ????

import { FieldNode, Registry, STRING } from '@furo/open-models/dist/index';

/**
 * @interface IDecimal
 *  Decimal numbers
 *   Regex pattern: ^[+-]?(\d*\.)?\d+$
 */
export interface IDecimal {
  /**
   *  Value is set as a quoted number, use your numeric parser of choice
   */
  value?: string;
}

/**
 * @interface TDecimal
 *  Decimal numbers
 *   Regex pattern: ^[+-]?(\d*\.)?\d+$
 */
export interface TDecimal {
  /**
   *  Value is set as a quoted number, use your numeric parser of choice
   */
  value?: string;
}

/**
 * Decimal
 *  Decimal numbers
 *   Regex pattern: ^[+-]?(\d*\.)?\d+$
 */
export class Decimal extends FieldNode {
  //  Value is set as a quoted number, use your numeric parser of choice
  private _value: STRING;

  public __defaultValues: IDecimal;

  constructor(
    initData?: IDecimal,
    parent?: FieldNode,
    parentAttributeName?: string,
  ) {
    super(undefined, parent, parentAttributeName);
    this.__meta.typeName = 'furo.type.Decimal';

    this.__meta.nodeFields = [
      {
        fieldName: 'value',
        protoName: 'value',
        FieldConstructor: STRING,
        constraints: {},
      },
    ];

    // Initialize the fields
    //  Value is set as a quoted number, use your numeric parser of choice
    this._value = new STRING(undefined, this, 'value');

    // Set required fields
    [].forEach(fieldName => {
      (this[fieldName as keyof Decimal] as FieldNode).__meta.required = true;
    });

    // Default values from openAPI annotations
    this.__defaultValues = {};

    // Initialize the fields with init data
    if (initData !== undefined) {
      this.__fromLiteral({ ...this.__defaultValues, ...initData });
    } else {
      this.__fromLiteral(this.__defaultValues);
    }

    // Set readonly fields after the init, so child nodes are readonly too
    [].forEach(fieldName => {
      (this[fieldName as keyof Decimal] as FieldNode).__readonly = true;
    });

    this.__meta.isPristine = true;
  }

  //  Value is set as a quoted number, use your numeric parser of choice
  public get value(): STRING {
    return this._value;
  }

  public set value(v: string) {
    this.__PrimitivesSetter(this._value, v);
  }

  fromLiteral(data: IDecimal) {
    super.__fromLiteral(data);
  }

  toLiteral(): IDecimal {
    return super.__toLiteral();
  }
}

Registry.register('furo.type.Decimal', Decimal);
