// Code generated by furo protoc-gen-open-models. DO NOT EDIT.
// protoc-gen-open-models version: ????

import { Fetcher } from '@furo/open-models/dist/Fetcher';
import { API_OPTIONS } from '../../API_OPTIONS';

import { ICubeServiceGetListRequest as IFuroCubeCubeServiceGetListRequest } from './CubeServiceGetListRequest';

import { ICubeServiceGetListResponse as IFuroCubeCubeServiceGetListResponse } from './CubeServiceGetListResponse';

import { ICubeServiceGetRequest as IFuroCubeCubeServiceGetRequest } from './CubeServiceGetRequest';

import { ICubeServiceGetResponse as IFuroCubeCubeServiceGetResponse } from './CubeServiceGetResponse';

import { ICubeServiceUpdateRequest as IFuroCubeCubeServiceUpdateRequest } from './CubeServiceUpdateRequest';

import { ICubeServiceUpdateResponse as IFuroCubeCubeServiceUpdateResponse } from './CubeServiceUpdateResponse';

//  cube services

export class CubeService {
  //  Get a list of cubes
  public GetList: Fetcher<
    IFuroCubeCubeServiceGetListRequest,
    IFuroCubeCubeServiceGetListResponse
  > = new Fetcher<
    IFuroCubeCubeServiceGetListRequest,
    IFuroCubeCubeServiceGetListResponse
  >(API_OPTIONS, 'GET', '/v1/cubes'); //  trailing

  public Get: Fetcher<
    IFuroCubeCubeServiceGetRequest,
    IFuroCubeCubeServiceGetResponse
  > = new Fetcher<
    IFuroCubeCubeServiceGetRequest,
    IFuroCubeCubeServiceGetResponse
  >(API_OPTIONS, 'GET', '/v1/cubes/{cube_id}');

  public Update: Fetcher<
    IFuroCubeCubeServiceUpdateRequest,
    IFuroCubeCubeServiceUpdateResponse
  > = new Fetcher<
    IFuroCubeCubeServiceUpdateRequest,
    IFuroCubeCubeServiceUpdateResponse
  >(API_OPTIONS, 'PUT', '/v1/cubes/{cube_id}', 'entity');
}
